receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${MY_POD_IP}:8888
  opencensus:
      endpoint: 0.0.0.0:55678


processors:
  batch:

exporters:
  logging:
      # loglevel: warn
      # sampling_initial: 2
      # sampling_thereafter: 500
  
  # otlp:
  #   endpoint: otelcol:4317
  
  prometheusremotewrite:
      endpoint: "http://prometheus:9090/api/v1/write"
      tls:
        insecure: true
      external_labels:
        environment: demo
      # headers:
      #   Authorization: "Bearer 1234"
      remote_write_queue:
        enabled: true
        queue_size: 5000
        num_consumers: 2

  jaeger:
      endpoint: jaeger:14250
      tls:
        insecure: true


extensions:
  health_check:
  pprof:
  zpages:

service:
  # extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]